name: stopwatch_app
description: A modern minimalist stopwatch application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter_launcher_icons:
  android: true
  image_path: "assets/images/Logo.png"
  adaptive_icon_background: "#0D1B2A"
  adaptive_icon_foreground: "assets/images/Logo.png"

flutter_native_splash:
  color: "#0D1B2A"
  image: "assets/images/Logo.png"
  android: true
  android_12:
    color: "#0D1B2A"
    image: "assets/images/Logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/